language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: 5.6

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script: ./libs/bin/parallel-lint app && ./libs/bin/parallel-lint -e php,phpt tests/cases && VERBOSE=true ./tests/run-tests.sh -p php tests/cases/

notifications:
  email: false
